### ISSUE TITLE
broken on darwin & windows

### ISSUE THREAD

**Issue by leehinman** [elastic/elastic-agent-system-metrics#109]
If we try to use elastic-agent-system-metrics for darwin or windows we get the following errors:

process_windows.go:41:32: undefined: names
process_windows.go:42:36: undefined: names

or

process_darwin.go:67:32: undefined: names
process_darwin.go:68:36: undefined: names

This was introduced by https://github.com/elastic/elastic-agent-system-metrics/pull/103

**Comment by leehinman** [comment]
@florianl can you please look at this since it was introduced by your PR?

**Comment by belimawr** [comment]
Revert PR to unblock `main`/new PRs: https://github.com/elastic/elastic-agent-system-metrics/pull/113

**Comment by florianl** [comment]
Pushed a PR with a fix in https://github.com/elastic/elastic-agent-system-metrics/pull/116.

**Comment by florianl** [comment]
Revert of the revert with https://github.com/elastic/elastic-agent-system-metrics/pull/117

**Comment by florianl** [comment]
With https://github.com/elastic/elastic-agent-system-metrics/pull/116 (the fix) and https://github.com/elastic/elastic-agent-system-metrics/pull/117 (the reintroduction of the revert) merged, I'm closing this issue.
